config/routes.rb
Rails.application.routes.draw do

  root to: 'articles#index'

  # Create
  get '/articles/new', to: 'articles#new', as: 'new_article'
  post '/articles', to: 'articles#create'

  # Update
  get '/articles/:id/edit', to: 'articles#edit', as: 'edit_article'
  patch '/articles/:id', to: 'articles#update'

  # All articles
  get '/articles', to: 'articles#index'

  # Specific article
  get '/articles/:id', to: 'articles#show', as: 'article'

  # Delete
  delete '/articles/:id', to: 'articles#destroy'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  validates :title, presence: true
  validates :content, presence: true

  def markdown_content
    Kramdown::Document.new(content).to_html.html_safe
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  def index
    @articles = Article.all
  end

  def show
  end

  def new
    @article = Article.new
  end

  def edit
  end

  def create
    @article = Article.new(article_params)

    if @article.save
      redirect_to @article, notice: 'Article was successfully created.'
    else
      render :new
    end
  end

  def update
    if @article.update(article_params)
      redirect_to @article, notice: 'Article was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @article.destroy
    redirect_to articles_url, notice: 'Article was successfully destroyed.'
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article, class: 'form') do |f| %>
  <%= f.text_field :title %>
  <%= f.text_area :content, data: { editor: 'markdown' }, rows: 10 %>
  <%= f.submit %>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1>WIKINONIMOUS</h1>
<p>Articles ABOUT EVERYTHING, anonymous</p>

<% @articles.each do |article| %>
  <article>
    <h2><%= link_to article.title, article %></h2>
    <%= article.content[0..100][2..-2] %>
  </article>
<% end %>

<%= link_to "Create", new_article_path()%>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<% content_for(:title) do %>
  Wikinimous - <%= @article.title %>
<% end %>

<article>
  <h1>
    <%= @article.title %>
    <small>
      <%= link_to edit_article_path(@article) do %><i class="fa fa-pencil"></i><% end %>

      <%= link_to article_path(@article), method: :delete, data: { confirm: 'Are you sure?' } do %>
        <i class="fa fa-trash-o"></i>
      <% end %>
    </small>
  </h1>

  <hr>
  <%= @article.markdown_content %>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for?(:title) ? yield(:title) : "Wikinimous" %></title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:300|Roboto+Slab">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wikinimous", root_path, class: 'navbar-brand' %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to 'New Article', new_article_path %>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

  <div class="container">
    <div class="row">
      <div class="col-sm-8 col-sm-offset-2">

        <%= yield %>
      </div>
    </div>
  </div>

</body>
</html>